### ISSUE TITLE
Basic documentation on how to use the plugin?

### ISSUE THREAD

**Issue by teivah** [logstash-plugins/logstash-output-jms#4]
Hello guys,

Would it be possible to have more information on how to use the plugin? It might be really useful but I'm struggling to configure things correctly..

Basically I tried to use the config example described here: [https://github.com/logstash-plugins/logstash-output-jms/blob/master/lib/logstash/outputs/jms.rb](https://github.com/logstash-plugins/logstash-output-jms/blob/master/lib/logstash/outputs/jms.rb). But without success so far...

Thanks

**Comment by AgentW4C** [comment]
There is an issue opened with core logstash team to get the docs published (https://github.com/elastic/logstash/issues/6667) so I wanted to continue with the documenting once the infrastructure is ready for that.

Anyway, could you be more specific about the versions (Java, Logstash, plugins) and the configuration you are using and the error you are getting, in order to have something to start with?
